version: "3.2"
services:
  python_dev:
    build: .
    volumes:
      - type: bind
        source: ./src
        target: /usr/app/src
        read_only: true
    stdin_open: true # -i
    tty: true # -t